"""JSON-primary task documents (``ar-task-document/v1``) and their markdown render.

The JSON document is the source of truth; ``task.md`` is a deterministic render
of it. This package owns the schema (``document``), the renderer (``render``),
and the read/write store (``store``); the ``task_doc`` MCP tool authors them and
the observer projects them (keyed by lifecycle).
"""

from __future__ import annotations

from agents_remember.models.task_intent import (
    AcceptanceObligationQuestion,
    ApprovedRequirementPacketRef,
    TaskIntentIdentity,
)

from .document import (
    TASK_DOCUMENT_SCHEMA,
    CodeExample,
    Decision,
    DiscardedSubTask,
    DiscardSourceProof,
    DiscardUnstartedProof,
    DocKind,
    DocStatus,
    HeaderNote,
    LeafPlacement,
    MasterExecutionNature,
    RouteReviewRecord,
    RouteReviewUnit,
    RouteReviewVerdict,
    Section,
    SprintExecutionEdge,
    SprintExecutionEndpoint,
    SprintExecutionGraph,
    SprintExecutionNode,
    SprintSeat,
    SprintSeatState,
    Step,
    StepDisposition,
    StepStatus,
    SubStep,
    SubTaskRef,
    TaskDocument,
    TaskEnclosureRef,
    TaskExecutionRegistration,
    current_step,
    derived_leaf_placement,
    leaf_placement_facts,
    numbering_drift_hints,
    resolve_graph_endpoint,
    series_done,
    series_total,
    step_done,
    step_total,
)
from .execution_graph_titles import (
    SprintGraphTitles,
    build_graph_titles,
    read_graph_titles,
)
from .readiness import CompletionBlocker, completion_blockers
from .render import render_markdown
from .store import (
    TaskDocSourceReadError,
    TaskDocSourceSnapshot,
    capture_task_doc_source,
    current_task_doc_source,
    doc_stem,
    json_path_for,
    markdown_path_for,
    missing_task_doc_source,
    read_task_doc,
    read_task_doc_with_source,
    write_task_doc,
    write_task_doc_batch,
    write_task_docs,
    write_task_docs_and_remove,
)

__all__ = [
    "TASK_DOCUMENT_SCHEMA",
    "AcceptanceObligationQuestion",
    "ApprovedRequirementPacketRef",
    "CodeExample",
    "CompletionBlocker",
    "Decision",
    "DiscardSourceProof",
    "DiscardUnstartedProof",
    "DiscardedSubTask",
    "DocKind",
    "DocStatus",
    "HeaderNote",
    "LeafPlacement",
    "MasterExecutionNature",
    "RouteReviewRecord",
    "RouteReviewUnit",
    "RouteReviewVerdict",
    "Section",
    "SprintExecutionEdge",
    "SprintExecutionEndpoint",
    "SprintExecutionGraph",
    "SprintExecutionNode",
    "SprintGraphTitles",
    "SprintSeat",
    "SprintSeatState",
    "Step",
    "StepDisposition",
    "StepStatus",
    "SubStep",
    "SubTaskRef",
    "TaskDocSourceReadError",
    "TaskDocSourceSnapshot",
    "TaskDocument",
    "TaskEnclosureRef",
    "TaskExecutionRegistration",
    "TaskIntentIdentity",
    "build_graph_titles",
    "capture_task_doc_source",
    "completion_blockers",
    "current_step",
    "current_task_doc_source",
    "derived_leaf_placement",
    "doc_stem",
    "json_path_for",
    "leaf_placement_facts",
    "markdown_path_for",
    "missing_task_doc_source",
    "numbering_drift_hints",
    "read_graph_titles",
    "read_task_doc",
    "read_task_doc_with_source",
    "render_markdown",
    "resolve_graph_endpoint",
    "series_done",
    "series_total",
    "step_done",
    "step_total",
    "write_task_doc",
    "write_task_doc_batch",
    "write_task_docs",
    "write_task_docs_and_remove",
]
